name: epic_narrator
channels:
  - pkgw/label/superseded # don't use pkgw-forge otherwise the ui will look broken
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pygobject
  - gtk3
  - matplotlib
  - pip:
    - python-vlc
    - sounddevice
    - soundfile
